### PR TITLE
Amd support using ROCm-smi and restored KDiffusionSampler.callback_state

### PR DESCRIPTION
**Pull request by w-e-w**
in responce to https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/pull/181

### New future
- add AMD support on linux using ROCm
reuse code from [holotape/stable-diffusion-webui-GPU-temperature-protection-rocm](https://github.com/holotape/stable-diffusion-webui-GPU-temperature-protection-rocm) (holotape credited as co-author for f71b82d)
@holotape can you confirm this is working
I have a bit of concerned about using ROCm like this, as I'm not sure if ROCm is persistent (like nvidia-smi) calling ROCm like this may cause lots of porcess to be spawned
image

### Bug fix
fix not restoring KDiffusionSampler.callback_state
it is is restored so that even if an error occurred during generation it will be restored

### To Do
documentation on ROCm
as I don't have AMD system I would prefer if `holotape` can do it

### Other
also @thecubist [thecubist/stable-diffusion-webui-CPU-temperature-protection-Windows](https://github.com/thecubist/stable-diffusion-webui-CPU-temperature-protection-Windows) if you wish you can make a PR to add CPU support

### CODE REVIEW

**Comment by VE3XYU** [comment]
Thank you, I am fine if you'd like to add this feature into yours.
**rocm-smi** is not persistent, and quits immediately, so there is no worry of multiple processes.
I will be happy to write the documentation for my side of it.

The way this is now, the extension **not working** when enabled in SD-webui 1.5.2.  
I get this output in the terminal and then SD-webui quits before starting the local server.

```
Traceback (most recent call last):
  File "/home/$user/stable-diffusion-webui/launch.py", line 39, in <module>
    main()
  File "/home/$user/stable-diffusion-webui/launch.py", line 35, in main
    start()
  File "/home/$user/stable-diffusion-webui/modules/launch_utils.py", line 394, in start
    webui.webui()
  File "/home/$user/stable-diffusion-webui/webui.py", line 393, in webui
    shared.demo = modules.ui.create_ui()
  File "/home/$user/stable-diffusion-webui/modules/ui.py", line 1460, in create_ui
    settings.create_ui(loadsave, dummy_component)
  File "/home/$user/stable-diffusion-webui/modules/ui_settings.py", line 107, in create_ui
    with gr.Blocks(analytics_enabled=False) as settings_interface:
  File "/home/$user/anaconda3/lib/python3.10/site-packages/gradio/blocks.py", line 1411, in __exit__
    self.config = self.get_config_file()
  File "/home/$user/anaconda3/lib/python3.10/site-packages/gradio/blocks.py", line 1389, in get_config_file
    block_config["example_inputs"] = block.example_inputs()  # type: ignore
  File "/home/$user/anaconda3/lib/python3.10/site-packages/gradio/components.py", line 1360, in example_inputs
    "raw": self.choices[0] if self.choices else None,
TypeError: 'dict_keys' object is not subscriptable
```

**Comment by w-e-w** [comment]
should be fixed now
gradio 3.32 cant take `<class 'dict_keys'>` as choice, need to converit to list

**Comment by VE3XYU** [comment]
Working now, all good.

**Comment by w-e-w** [comment]
if you can't try making it to work for multi GPU for AMD with `GPU device index`
but chances are you may not have multiple AMD gpus you may not be able to test

note: the info box in the screenshot only shows in 1.6.0

to be honest I only wrote this extension to shut people up because people are asking for this bad last resort of a method to keep temperature down
I'm quite surprised that some people actually want to use it
> I don't use this myself

**Comment by VE3XYU** [comment]
It helps keep the fan noise down if I am doing something like generating XYZ while multitasking. I still use another program that controls my fan curve to actually protect from overheating.

Sorry, which screenshot? edit: nvm, I see

I have another AMD GPU but not installed in the same PC. I will consider.

**Pull request merged**
