### PR TITLE
First pass at start temp feature

### PR DESCRIPTION
**Pull request by ajs**
I added an option to not start generation until the temp was at or below a max threshold. This allows you to have a much more restrictive start temp than your cutoff during generation.

I considered giving it its own sleep max time, but I don't think that's strictly necessary and would further clutter the settings UI.

Speaking of settings, I didn't want to tackle it in this pull request to muddy the water, but this module should be categorized in settings now that that's a thing.

### CODE REVIEW

**Comment by w-e-w** [comment]
is your intention to limit the starting temperature of the "entire job" or the starting temperature of "a batch"
because unless I miss remembered `process` is called on every batch and not once per job

I also won't set the default value to 40°C which is very low
some computers don't drop below 40°C even on idle
I don't want it to have high chance of getting stuck on default settings
it's a user wishes to start a generation at 40°C, then they should configurate themselves

**Comment by ajs** [comment]
On batch vs job, I wasn't clear on that distinction (API docs are difficult to digest) but I think that per-batch is fine. For ME the goal is to press "generate" and not worry about waiting until the temp comes down from the last generation.

For the temp, yeah, that's fair. It's really not even always hit on my system. What would you recommend, 45? Note that this is turned off by default, so it won't affect anyone's behavior unless they go turn it on in settings.

**Comment by w-e-w** [comment]
> because unless I miss remembered process is called on every batch and not once per job

well, apparently I did misremembered

I got `process` and `process_batch` mixed up, `process` is only runed at start of job
(unless you are using scripts like xyz grid)

---

>...... This allows you to have a much more restrictive start temp than your cutoff during generation.

I'm being thinking about this and I'm still not convinced this is useful, can you explain the reason why you want to do so?

I'm not convinced that you would need two temperature values would help control the temperature better

unless you are trying to to only restrict the starting temperature and not the generation temperature

if this is the case then I would prefer to make it an option to choise where the temperature restriction is applyed
`starting of job` `starting of batch` or `during generation`

**Comment by ajs** [comment]
Hi there. I use this routinely now, so it's definitely useful to at least one user ;-)

The desired behavior for me is to never pause during generation. Once it starts, I want it to finish. But that can be hard to achieve given that I'm in winter where I am, and so the heat is on in the house, keeping everything much warming than in the summer when the AC is running, compensating for not just the outside temp, but also my machine.

So I want the card to be as close to baseline temp as possible at start, not just "lower than the red line."

I would never want the system to say, "your card is now 42 degrees F, I'm going to pause a few seconds for it to cool," but doing so at startup is a negligible cost.

This is particularly helpful when I'm doing generation after generation to test out an idea, and I might tweak settings and prompt and then regenerate a dozen or two times in a row. Each generation may pause for a bit when it starts, but never has to do so during execution, which I consider a win, and probably degrades my card slower than operating as close to the line as I can get.

**Comment by w-e-w** [comment]
@ajs hello, ping again
- https://github.com/w-e-w/stable-diffusion-webui-GPU-temperature-protection/pull/7

**Comment by w-e-w** [comment]
@ajs knock knock anyone home

**Pull request closed without merging**
